### ISSUE TITLE
[showcase] Some data cannot be loaded (examples provided) - and we need to explain why (and display errors nicely in general)

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/frontend-oddk#23]
**Moved from gitlab**

What it tells me is we have to improve showcase (JS part maybe) so we catch these kind of errors and show them to the user - otherwise user blames CKAN. Can we open issues for that on next gen with these examples.

* example of serving data over HTTP instead of HTTPS which causes the mixed content error
  * https://frontend-v2-openddk.herokuapp.com/city-of-copenhagen/afmaerkning_total
* example of invalid JSON: `Uncaught (in promise) SyntaxError: Unexpected token e in JSON at position 77190006`:
  * http://wfs-kbhkort.kk.dk/k101/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=k101:afmaerkning_total&outputFormat=application%2Fjson&SRSNAME=EPSG:4326

## Acceptance criteria

* [x] when I visit a page with mixed content, I have information message explaining why the previews cannot be loaded
* [ ] when I visit a page with invalid JSON data, I have a nice message explaining it and suggesting to contact the publisher about the error

## Tasks

* [x] handle mixed content error in datapackage-views-js
* [ ] handle invalid JSON (or any other data) error in datapackage-views-js
* [ ] display error message nicely and suggest reporting the issue somewhere, eg, on publisher's issue tracker or by just contacting them

**Comment by anuveyatsu** [comment]
Comments:

Rufus:

> mixed content we can't do anything about atm. We can explain the issue though.

Paul Walsh:

> Mixed content can be solved using a proxy server I wrote at OKI and hosting on our infra somewhere (or, write a new one): https://github.com/okfn/gobetween

Anu:

> Mixed content FIXED by proxy plugin
