### ISSUE TITLE
[Epic] i18n for the site and metadata

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/frontend-oddk#55]
## Tasks

Staging environment work

* [ ] Enable i18n for the site so that users can get either the English or Danish version of the site based on their browser's settings.
* [ ] Install and adapt fluent extension
* [x] #56
* [ ] Integration of backend with translations API
* [ ] Integrate frontend with translated metadata fields

Production environment work (to be done once everything is implemented and tested on staging)

TODO
