### ISSUE TITLE
Extension for translations API

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/frontend-oddk#56]
## Acceptance criteria

* [ ] I have an extension for CKAN that exposes APIs for string translation

## Tasks

* [x] Create a repo and setup an extension at `github.com/datopian/ckanext-translate`
* [x] Write a README explaining what exactly this extension is for
* [x] Create an API for translating strings `/api/action/translate`
  * [x] which requires auth key and user must have a permission to create datasets
  * [x] accepts POST request
  * [ ] expects `text`, `from` and `to` parameters in the body
  * [x] returns JSON response with `text` which is translated result of the provided input
  * [x] integrate IBM translation API
  * [x] handle errors

**Comment by sagargg** [comment]
Closing as **DONE**. I belive it's already implemented.
